//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoSomething.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DoSomething.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string PlaceInfoPage {
            get {
                return ResourceManager.GetString("PlaceInfoPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string PostItemParamPage {
            get {
                return ResourceManager.GetString("PostItemParamPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CREATE OR ALTER PROCEDURE SETPARAMVALUES(PARAMPLACEID SMALLINT, PARAMID INTEGER, DATATYPEID SMALLINT, VAL VARCHAR(2048))
        ///RETURNS (SYSTYPEID SMALLINT)
        ///AS
        ///	DECLARE VARIABLE VALI NUMERIC(18,0);
        ///	DECLARE VARIABLE VALS VARCHAR(2048);
        ///	DECLARE VARIABLE VALB BLOB SUB_TYPE 0 SEGMENT SIZE 80;
        ///	DECLARE VARIABLE FLAG INTEGER;
        ///	DECLARE VARIABLE TMP SMALLINT;
        ///BEGIN
        ///	IF (:PARAMID IS NULL OR :DATATYPEID IS NULL) THEN
        ///		BEGIN
        ///			SYSTYPEID = -1;
        ///			SUSPEND;
        ///			EXIT;
        ///		END
        ///
        ///	VALI=NULL;
        ///	VALS=NULL;
        ///	VALB=NUL [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string SetParamValues {
            get {
                return ResourceManager.GetString("SetParamValues", resourceCulture);
            }
        }
    }
}
